# -*- coding: utf-8 -*-
"""dot_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RsMIN0XY8lF271vB_Vdn4tgC1jy87-dO
"""

import numpy as np
import tensorflow as tf

x = x =  np.array([[5, 78, 2, 34, 0],
                    [6, 79, 3, 35, 1],
                    [7, 80, 4, 36, 2]])

y = x =  np.array([[5, 78, 2, 34, 0],
                    [6, 79, 3, 35, 1],
                    [7, 80, 4, 36, 2]])


#dot using numpy
def dot_using_numpy(x,y):
  x1 = tf.reshape(x,[-1])
  y1 = tf.reshape(y,[-1])
  z = np.dot(x1, y1)
  return z


#dot using loop
def dot_using_loop(x, y):
  x = tf.reshape(x,[-1])
  y = tf.reshape(y,[-1])
  z = 0
  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return float(z)

my_dot_using_loop = dot_using_loop(x, y)
my_dot_using_numpy = dot_using_numpy(x,y)
print(my_dot_using_loop)
print(my_dot_using_numpy)